package org.molgenis.api.identities;

import com.google.auto.value.AutoValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.molgenis.data.security.auth.VOGroup;

@AutoValue
@ApiModel(description = "A group that is managed remotely in a virtual organisation (VO)")
@SuppressWarnings("java:S1610") // Abstract classes without fields should be converted to interfaces
public abstract class VOGroupResponse {
  @ApiModelProperty("ID of the VO group, generated by MOLGENIS")
  public abstract String getId();

  @ApiModelProperty("Name of the VO group, assigned by the virtual organisation")
  public abstract String getName();

  static VOGroupResponse fromEntity(VOGroup group) {
    return new AutoValue_VOGroupResponse(group.getId(), group.getName());
  }
}
