export default {
  numberOfSamples: 0,
  transcriptome: false,
  methylome: false,
  genotypes: false,
  wbcc: false,
  metabolome: false,
  wgs: false,
  male: false,
  female: false,
  smoking: false,
  nonSmoking: false,
  belowTwenty: true,
  twentyThirty: true,
  thirtyFourty: true,
  fourtyFifty: true,
  fiftySixty: true,
  sixtySeventy: true,
  seventyEighty: true,
  aboveEigthy: true,
  biobank: null,
  aggs: [],
  biobanks: [],
  charts: {
    gender: null,
    smoking: null,
    data_types: null,
    age: null
  },
  apiUrl: 'https://molgenis09.gcc.rug.nl/api/',
  token: 'test'
}
