//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//


package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="departmentOrDivision" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entityName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entityNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="floorOrPremises" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="postOfficeBox" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="streetPostDirectional" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="streetPreDirectional" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="streetOrThoroughfareNameAndType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="streetOrThoroughfareNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="streetOrThoroughfareSectionName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="streetOrThoroughfareExtensionName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address")
public class Address {

    @XmlAttribute
    protected String city;
    @XmlAttribute
    protected String country;
    @XmlAttribute
    protected String departmentOrDivision;
    @XmlAttribute
    protected String entityName;
    @XmlAttribute
    protected String entityNumber;
    @XmlAttribute
    protected String floorOrPremises;
    @XmlAttribute
    protected String postOfficeBox;
    @XmlAttribute
    protected String zipCode;
    @XmlAttribute
    protected String state;
    @XmlAttribute
    protected String streetPostDirectional;
    @XmlAttribute
    protected String streetPreDirectional;
    @XmlAttribute
    protected String streetOrThoroughfareNameAndType;
    @XmlAttribute
    protected String streetOrThoroughfareNumber;
    @XmlAttribute
    protected String streetOrThoroughfareSectionName;
    @XmlAttribute
    protected String streetOrThoroughfareExtensionName;
    @XmlAttribute
    protected Integer id;

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the departmentOrDivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentOrDivision() {
        return departmentOrDivision;
    }

    /**
     * Sets the value of the departmentOrDivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentOrDivision(String value) {
        this.departmentOrDivision = value;
    }

    /**
     * Gets the value of the entityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * Sets the value of the entityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityName(String value) {
        this.entityName = value;
    }

    /**
     * Gets the value of the entityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityNumber() {
        return entityNumber;
    }

    /**
     * Sets the value of the entityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityNumber(String value) {
        this.entityNumber = value;
    }

    /**
     * Gets the value of the floorOrPremises property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloorOrPremises() {
        return floorOrPremises;
    }

    /**
     * Sets the value of the floorOrPremises property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloorOrPremises(String value) {
        this.floorOrPremises = value;
    }

    /**
     * Gets the value of the postOfficeBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostOfficeBox() {
        return postOfficeBox;
    }

    /**
     * Sets the value of the postOfficeBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostOfficeBox(String value) {
        this.postOfficeBox = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the streetPostDirectional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetPostDirectional() {
        return streetPostDirectional;
    }

    /**
     * Sets the value of the streetPostDirectional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetPostDirectional(String value) {
        this.streetPostDirectional = value;
    }

    /**
     * Gets the value of the streetPreDirectional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetPreDirectional() {
        return streetPreDirectional;
    }

    /**
     * Sets the value of the streetPreDirectional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetPreDirectional(String value) {
        this.streetPreDirectional = value;
    }

    /**
     * Gets the value of the streetOrThoroughfareNameAndType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetOrThoroughfareNameAndType() {
        return streetOrThoroughfareNameAndType;
    }

    /**
     * Sets the value of the streetOrThoroughfareNameAndType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetOrThoroughfareNameAndType(String value) {
        this.streetOrThoroughfareNameAndType = value;
    }

    /**
     * Gets the value of the streetOrThoroughfareNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetOrThoroughfareNumber() {
        return streetOrThoroughfareNumber;
    }

    /**
     * Sets the value of the streetOrThoroughfareNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetOrThoroughfareNumber(String value) {
        this.streetOrThoroughfareNumber = value;
    }

    /**
     * Gets the value of the streetOrThoroughfareSectionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetOrThoroughfareSectionName() {
        return streetOrThoroughfareSectionName;
    }

    /**
     * Sets the value of the streetOrThoroughfareSectionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetOrThoroughfareSectionName(String value) {
        this.streetOrThoroughfareSectionName = value;
    }

    /**
     * Gets the value of the streetOrThoroughfareExtensionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetOrThoroughfareExtensionName() {
        return streetOrThoroughfareExtensionName;
    }

    /**
     * Sets the value of the streetOrThoroughfareExtensionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetOrThoroughfareExtensionName(String value) {
        this.streetOrThoroughfareExtensionName = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

}
