//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//


package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotationAvailabilityProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotationAvailabilityProfile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="providesInformationTo" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}CollectionProtocol" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="hasAdditionalPatientDemographics" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasExposureHistory" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasFamilyHistory" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasHistopathologicInformation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasLabData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasLongitudinalSpecimens" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasMatchedSpecimens" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasOutcomeInformation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasParticipantsAvailableForFollowup" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasTreatmentInformation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotationAvailabilityProfile", propOrder = {
    "providesInformationTo"
})
public class AnnotationAvailabilityProfile {

    protected AnnotationAvailabilityProfile.ProvidesInformationTo providesInformationTo;
    @XmlAttribute
    protected Boolean hasAdditionalPatientDemographics;
    @XmlAttribute
    protected Boolean hasExposureHistory;
    @XmlAttribute
    protected Boolean hasFamilyHistory;
    @XmlAttribute
    protected Boolean hasHistopathologicInformation;
    @XmlAttribute
    protected Boolean hasLabData;
    @XmlAttribute
    protected Boolean hasLongitudinalSpecimens;
    @XmlAttribute
    protected Boolean hasMatchedSpecimens;
    @XmlAttribute
    protected Boolean hasOutcomeInformation;
    @XmlAttribute
    protected Boolean hasParticipantsAvailableForFollowup;
    @XmlAttribute
    protected Boolean hasTreatmentInformation;
    @XmlAttribute
    protected Integer id;

    /**
     * Gets the value of the providesInformationTo property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationAvailabilityProfile.ProvidesInformationTo }
     *     
     */
    public AnnotationAvailabilityProfile.ProvidesInformationTo getProvidesInformationTo() {
        return providesInformationTo;
    }

    /**
     * Sets the value of the providesInformationTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationAvailabilityProfile.ProvidesInformationTo }
     *     
     */
    public void setProvidesInformationTo(AnnotationAvailabilityProfile.ProvidesInformationTo value) {
        this.providesInformationTo = value;
    }

    /**
     * Gets the value of the hasAdditionalPatientDemographics property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasAdditionalPatientDemographics() {
        return hasAdditionalPatientDemographics;
    }

    /**
     * Sets the value of the hasAdditionalPatientDemographics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasAdditionalPatientDemographics(Boolean value) {
        this.hasAdditionalPatientDemographics = value;
    }

    /**
     * Gets the value of the hasExposureHistory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasExposureHistory() {
        return hasExposureHistory;
    }

    /**
     * Sets the value of the hasExposureHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasExposureHistory(Boolean value) {
        this.hasExposureHistory = value;
    }

    /**
     * Gets the value of the hasFamilyHistory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasFamilyHistory() {
        return hasFamilyHistory;
    }

    /**
     * Sets the value of the hasFamilyHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasFamilyHistory(Boolean value) {
        this.hasFamilyHistory = value;
    }

    /**
     * Gets the value of the hasHistopathologicInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasHistopathologicInformation() {
        return hasHistopathologicInformation;
    }

    /**
     * Sets the value of the hasHistopathologicInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasHistopathologicInformation(Boolean value) {
        this.hasHistopathologicInformation = value;
    }

    /**
     * Gets the value of the hasLabData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasLabData() {
        return hasLabData;
    }

    /**
     * Sets the value of the hasLabData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasLabData(Boolean value) {
        this.hasLabData = value;
    }

    /**
     * Gets the value of the hasLongitudinalSpecimens property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasLongitudinalSpecimens() {
        return hasLongitudinalSpecimens;
    }

    /**
     * Sets the value of the hasLongitudinalSpecimens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasLongitudinalSpecimens(Boolean value) {
        this.hasLongitudinalSpecimens = value;
    }

    /**
     * Gets the value of the hasMatchedSpecimens property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasMatchedSpecimens() {
        return hasMatchedSpecimens;
    }

    /**
     * Sets the value of the hasMatchedSpecimens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasMatchedSpecimens(Boolean value) {
        this.hasMatchedSpecimens = value;
    }

    /**
     * Gets the value of the hasOutcomeInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasOutcomeInformation() {
        return hasOutcomeInformation;
    }

    /**
     * Sets the value of the hasOutcomeInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasOutcomeInformation(Boolean value) {
        this.hasOutcomeInformation = value;
    }

    /**
     * Gets the value of the hasParticipantsAvailableForFollowup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasParticipantsAvailableForFollowup() {
        return hasParticipantsAvailableForFollowup;
    }

    /**
     * Sets the value of the hasParticipantsAvailableForFollowup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasParticipantsAvailableForFollowup(Boolean value) {
        this.hasParticipantsAvailableForFollowup = value;
    }

    /**
     * Gets the value of the hasTreatmentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasTreatmentInformation() {
        return hasTreatmentInformation;
    }

    /**
     * Sets the value of the hasTreatmentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasTreatmentInformation(Boolean value) {
        this.hasTreatmentInformation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}CollectionProtocol" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "collectionProtocol"
    })
    public static class ProvidesInformationTo {

        @XmlElement(name = "CollectionProtocol")
        protected List<CollectionProtocol> collectionProtocol;

        /**
         * Gets the value of the collectionProtocol property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the collectionProtocol property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCollectionProtocol().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CollectionProtocol }
         * 
         * 
         */
        public List<CollectionProtocol> getCollectionProtocol() {
            if (collectionProtocol == null) {
                collectionProtocol = new ArrayList<CollectionProtocol>();
            }
            return this.collectionProtocol;
        }

    }

}
