//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//


package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CollectionProtocol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CollectionProtocol">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="enrolls" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}ParticipantCollectionSummary" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="residesAt" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}Institution" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="isConstrainedBy" type="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}SpecimenAvailabilitySummaryProfile" form="qualified"/>
 *         &lt;element name="makesAvailable" type="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}AnnotationAvailabilityProfile" form="qualified"/>
 *         &lt;element name="isAssignedTo" type="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}SpecimenCollectionContact" form="qualified"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dateLastUpdated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CollectionProtocol", propOrder = {
    "enrolls",
    "residesAt",
    "isConstrainedBy",
    "makesAvailable",
    "isAssignedTo"
})
public class CollectionProtocol {

    protected CollectionProtocol.Enrolls enrolls;
    protected CollectionProtocol.ResidesAt residesAt;
    @XmlElement(required = true)
    protected SpecimenAvailabilitySummaryProfile isConstrainedBy;
    @XmlElement(required = true)
    protected AnnotationAvailabilityProfile makesAvailable;
    @XmlElement(required = true)
    protected SpecimenCollectionContact isAssignedTo;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateLastUpdated;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String identifier;

    /**
     * Gets the value of the enrolls property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionProtocol.Enrolls }
     *     
     */
    public CollectionProtocol.Enrolls getEnrolls() {
        return enrolls;
    }

    /**
     * Sets the value of the enrolls property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionProtocol.Enrolls }
     *     
     */
    public void setEnrolls(CollectionProtocol.Enrolls value) {
        this.enrolls = value;
    }

    /**
     * Gets the value of the residesAt property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionProtocol.ResidesAt }
     *     
     */
    public CollectionProtocol.ResidesAt getResidesAt() {
        return residesAt;
    }

    /**
     * Sets the value of the residesAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionProtocol.ResidesAt }
     *     
     */
    public void setResidesAt(CollectionProtocol.ResidesAt value) {
        this.residesAt = value;
    }

    /**
     * Gets the value of the isConstrainedBy property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenAvailabilitySummaryProfile }
     *     
     */
    public SpecimenAvailabilitySummaryProfile getIsConstrainedBy() {
        return isConstrainedBy;
    }

    /**
     * Sets the value of the isConstrainedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenAvailabilitySummaryProfile }
     *     
     */
    public void setIsConstrainedBy(SpecimenAvailabilitySummaryProfile value) {
        this.isConstrainedBy = value;
    }

    /**
     * Gets the value of the makesAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationAvailabilityProfile }
     *     
     */
    public AnnotationAvailabilityProfile getMakesAvailable() {
        return makesAvailable;
    }

    /**
     * Sets the value of the makesAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationAvailabilityProfile }
     *     
     */
    public void setMakesAvailable(AnnotationAvailabilityProfile value) {
        this.makesAvailable = value;
    }

    /**
     * Gets the value of the isAssignedTo property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenCollectionContact }
     *     
     */
    public SpecimenCollectionContact getIsAssignedTo() {
        return isAssignedTo;
    }

    /**
     * Sets the value of the isAssignedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenCollectionContact }
     *     
     */
    public void setIsAssignedTo(SpecimenCollectionContact value) {
        this.isAssignedTo = value;
    }

    /**
     * Gets the value of the dateLastUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateLastUpdated() {
        return dateLastUpdated;
    }

    /**
     * Sets the value of the dateLastUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateLastUpdated(XMLGregorianCalendar value) {
        this.dateLastUpdated = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}ParticipantCollectionSummary" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "participantCollectionSummary"
    })
    public static class Enrolls {

        @XmlElement(name = "ParticipantCollectionSummary", required = true)
        protected List<ParticipantCollectionSummary> participantCollectionSummary;

        /**
         * Gets the value of the participantCollectionSummary property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the participantCollectionSummary property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParticipantCollectionSummary().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ParticipantCollectionSummary }
         * 
         * 
         */
        public List<ParticipantCollectionSummary> getParticipantCollectionSummary() {
            if (participantCollectionSummary == null) {
                participantCollectionSummary = new ArrayList<ParticipantCollectionSummary>();
            }
            return this.participantCollectionSummary;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}Institution" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "institution"
    })
    public static class ResidesAt {

        @XmlElement(name = "Institution", required = true)
        protected List<Institution> institution;

        /**
         * Gets the value of the institution property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the institution property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstitution().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Institution }
         * 
         * 
         */
        public List<Institution> getInstitution() {
            if (institution == null) {
                institution = new ArrayList<Institution>();
            }
            return this.institution;
        }

    }

}
