//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//


package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Address_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "Address");
    private final static QName _PatientAgeGroupAtCollection_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "PatientAgeGroupAtCollection");
    private final static QName _Diagnosis_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "Diagnosis");
    private final static QName _ParticipantCollectionSummary_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "ParticipantCollectionSummary");
    private final static QName _Person_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "Person");
    private final static QName _Preservation_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "Preservation");
    private final static QName _CbmNode_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "CbmNode");
    private final static QName _SpecimenAvailabilitySummaryProfile_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "SpecimenAvailabilitySummaryProfile");
    private final static QName _SpecimenCollectionContact_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "SpecimenCollectionContact");
    private final static QName _CollectionProtocol_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "CollectionProtocol");
    private final static QName _Institution_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "Institution");
    private final static QName _AnnotationAvailabilityProfile_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "AnnotationAvailabilityProfile");
    private final static QName _Organization_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "Organization");
    private final static QName _SpecimenCollectionSummary_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "SpecimenCollectionSummary");
    private final static QName _Race_QNAME = new QName("gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", "Race");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpecimenCollectionContact }
     * 
     */
    public SpecimenCollectionContact createSpecimenCollectionContact() {
        return new SpecimenCollectionContact();
    }

    /**
     * Create an instance of {@link Preservation }
     * 
     */
    public Preservation createPreservation() {
        return new Preservation();
    }

    /**
     * Create an instance of {@link AnnotationAvailabilityProfile }
     * 
     */
    public AnnotationAvailabilityProfile createAnnotationAvailabilityProfile() {
        return new AnnotationAvailabilityProfile();
    }

    /**
     * Create an instance of {@link Preservation.IsAppliedTo }
     * 
     */
    public Preservation.IsAppliedTo createPreservationIsAppliedTo() {
        return new Preservation.IsAppliedTo();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link CbmNode }
     * 
     */
    public CbmNode createCbmNode() {
        return new CbmNode();
    }

    /**
     * Create an instance of {@link CollectionProtocol.ResidesAt }
     * 
     */
    public CollectionProtocol.ResidesAt createCollectionProtocolResidesAt() {
        return new CollectionProtocol.ResidesAt();
    }

    /**
     * Create an instance of {@link CollectionProtocol.Enrolls }
     * 
     */
    public CollectionProtocol.Enrolls createCollectionProtocolEnrolls() {
        return new CollectionProtocol.Enrolls();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Institution }
     * 
     */
    public Institution createInstitution() {
        return new Institution();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link PatientAgeGroupAtCollection.DescribesPatientAge }
     * 
     */
    public PatientAgeGroupAtCollection.DescribesPatientAge createPatientAgeGroupAtCollectionDescribesPatientAge() {
        return new PatientAgeGroupAtCollection.DescribesPatientAge();
    }

    /**
     * Create an instance of {@link Race }
     * 
     */
    public Race createRace() {
        return new Race();
    }

    /**
     * Create an instance of {@link ParticipantCollectionSummary }
     * 
     */
    public ParticipantCollectionSummary createParticipantCollectionSummary() {
        return new ParticipantCollectionSummary();
    }

    /**
     * Create an instance of {@link ParticipantCollectionSummary.IsClassifiedBy }
     * 
     */
    public ParticipantCollectionSummary.IsClassifiedBy createParticipantCollectionSummaryIsClassifiedBy() {
        return new ParticipantCollectionSummary.IsClassifiedBy();
    }

    /**
     * Create an instance of {@link SpecimenCollectionSummary }
     * 
     */
    public SpecimenCollectionSummary createSpecimenCollectionSummary() {
        return new SpecimenCollectionSummary();
    }

    /**
     * Create an instance of {@link Diagnosis }
     * 
     */
    public Diagnosis createDiagnosis() {
        return new Diagnosis();
    }

    /**
     * Create an instance of {@link ParticipantCollectionSummary.Provides }
     * 
     */
    public ParticipantCollectionSummary.Provides createParticipantCollectionSummaryProvides() {
        return new ParticipantCollectionSummary.Provides();
    }

    /**
     * Create an instance of {@link PatientAgeGroupAtCollection }
     * 
     */
    public PatientAgeGroupAtCollection createPatientAgeGroupAtCollection() {
        return new PatientAgeGroupAtCollection();
    }

    /**
     * Create an instance of {@link CollectionProtocol }
     * 
     */
    public CollectionProtocol createCollectionProtocol() {
        return new CollectionProtocol();
    }

    /**
     * Create an instance of {@link CbmNode.Protocols }
     * 
     */
    public CbmNode.Protocols createCbmNodeProtocols() {
        return new CbmNode.Protocols();
    }

    /**
     * Create an instance of {@link SpecimenAvailabilitySummaryProfile }
     * 
     */
    public SpecimenAvailabilitySummaryProfile createSpecimenAvailabilitySummaryProfile() {
        return new SpecimenAvailabilitySummaryProfile();
    }

    /**
     * Create an instance of {@link SpecimenAvailabilitySummaryProfile.RestrictsAccessTo }
     * 
     */
    public SpecimenAvailabilitySummaryProfile.RestrictsAccessTo createSpecimenAvailabilitySummaryProfileRestrictsAccessTo() {
        return new SpecimenAvailabilitySummaryProfile.RestrictsAccessTo();
    }

    /**
     * Create an instance of {@link ParticipantCollectionSummary.Receives }
     * 
     */
    public ParticipantCollectionSummary.Receives createParticipantCollectionSummaryReceives() {
        return new ParticipantCollectionSummary.Receives();
    }

    /**
     * Create an instance of {@link AnnotationAvailabilityProfile.ProvidesInformationTo }
     * 
     */
    public AnnotationAvailabilityProfile.ProvidesInformationTo createAnnotationAvailabilityProfileProvidesInformationTo() {
        return new AnnotationAvailabilityProfile.ProvidesInformationTo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "Address")
    public JAXBElement<Address> createAddress(Address value) {
        return new JAXBElement<Address>(_Address_QNAME, Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientAgeGroupAtCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "PatientAgeGroupAtCollection")
    public JAXBElement<PatientAgeGroupAtCollection> createPatientAgeGroupAtCollection(PatientAgeGroupAtCollection value) {
        return new JAXBElement<PatientAgeGroupAtCollection>(_PatientAgeGroupAtCollection_QNAME, PatientAgeGroupAtCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagnosis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "Diagnosis")
    public JAXBElement<Diagnosis> createDiagnosis(Diagnosis value) {
        return new JAXBElement<Diagnosis>(_Diagnosis_QNAME, Diagnosis.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParticipantCollectionSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "ParticipantCollectionSummary")
    public JAXBElement<ParticipantCollectionSummary> createParticipantCollectionSummary(ParticipantCollectionSummary value) {
        return new JAXBElement<ParticipantCollectionSummary>(_ParticipantCollectionSummary_QNAME, ParticipantCollectionSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "Person")
    public JAXBElement<Person> createPerson(Person value) {
        return new JAXBElement<Person>(_Person_QNAME, Person.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Preservation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "Preservation")
    public JAXBElement<Preservation> createPreservation(Preservation value) {
        return new JAXBElement<Preservation>(_Preservation_QNAME, Preservation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CbmNode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "CbmNode")
    public JAXBElement<CbmNode> createCbmNode(CbmNode value) {
        return new JAXBElement<CbmNode>(_CbmNode_QNAME, CbmNode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecimenAvailabilitySummaryProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "SpecimenAvailabilitySummaryProfile")
    public JAXBElement<SpecimenAvailabilitySummaryProfile> createSpecimenAvailabilitySummaryProfile(SpecimenAvailabilitySummaryProfile value) {
        return new JAXBElement<SpecimenAvailabilitySummaryProfile>(_SpecimenAvailabilitySummaryProfile_QNAME, SpecimenAvailabilitySummaryProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecimenCollectionContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "SpecimenCollectionContact")
    public JAXBElement<SpecimenCollectionContact> createSpecimenCollectionContact(SpecimenCollectionContact value) {
        return new JAXBElement<SpecimenCollectionContact>(_SpecimenCollectionContact_QNAME, SpecimenCollectionContact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CollectionProtocol }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "CollectionProtocol")
    public JAXBElement<CollectionProtocol> createCollectionProtocol(CollectionProtocol value) {
        return new JAXBElement<CollectionProtocol>(_CollectionProtocol_QNAME, CollectionProtocol.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Institution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "Institution")
    public JAXBElement<Institution> createInstitution(Institution value) {
        return new JAXBElement<Institution>(_Institution_QNAME, Institution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationAvailabilityProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "AnnotationAvailabilityProfile")
    public JAXBElement<AnnotationAvailabilityProfile> createAnnotationAvailabilityProfile(AnnotationAvailabilityProfile value) {
        return new JAXBElement<AnnotationAvailabilityProfile>(_AnnotationAvailabilityProfile_QNAME, AnnotationAvailabilityProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "Organization")
    public JAXBElement<Organization> createOrganization(Organization value) {
        return new JAXBElement<Organization>(_Organization_QNAME, Organization.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecimenCollectionSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "SpecimenCollectionSummary")
    public JAXBElement<SpecimenCollectionSummary> createSpecimenCollectionSummary(SpecimenCollectionSummary value) {
        return new JAXBElement<SpecimenCollectionSummary>(_SpecimenCollectionSummary_QNAME, SpecimenCollectionSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Race }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", name = "Race")
    public JAXBElement<Race> createRace(Race value) {
        return new JAXBElement<Race>(_Race_QNAME, Race.class, null, value);
    }

}
