//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;
