//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//


package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParticipantCollectionSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParticipantCollectionSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isClassifiedBy" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}Race" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="provides" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}SpecimenCollectionSummary" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="receives" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}Diagnosis" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="participantCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ethnicity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gender" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParticipantCollectionSummary", propOrder = {
    "isClassifiedBy",
    "provides",
    "receives"
})
public class ParticipantCollectionSummary {

    protected ParticipantCollectionSummary.IsClassifiedBy isClassifiedBy;
    protected ParticipantCollectionSummary.Provides provides;
    protected ParticipantCollectionSummary.Receives receives;
    @XmlAttribute
    protected Integer participantCount;
    @XmlAttribute
    protected String ethnicity;
    @XmlAttribute
    protected String gender;
    @XmlAttribute
    protected Integer id;

    /**
     * Gets the value of the isClassifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantCollectionSummary.IsClassifiedBy }
     *     
     */
    public ParticipantCollectionSummary.IsClassifiedBy getIsClassifiedBy() {
        return isClassifiedBy;
    }

    /**
     * Sets the value of the isClassifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantCollectionSummary.IsClassifiedBy }
     *     
     */
    public void setIsClassifiedBy(ParticipantCollectionSummary.IsClassifiedBy value) {
        this.isClassifiedBy = value;
    }

    /**
     * Gets the value of the provides property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantCollectionSummary.Provides }
     *     
     */
    public ParticipantCollectionSummary.Provides getProvides() {
        return provides;
    }

    /**
     * Sets the value of the provides property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantCollectionSummary.Provides }
     *     
     */
    public void setProvides(ParticipantCollectionSummary.Provides value) {
        this.provides = value;
    }

    /**
     * Gets the value of the receives property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantCollectionSummary.Receives }
     *     
     */
    public ParticipantCollectionSummary.Receives getReceives() {
        return receives;
    }

    /**
     * Sets the value of the receives property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantCollectionSummary.Receives }
     *     
     */
    public void setReceives(ParticipantCollectionSummary.Receives value) {
        this.receives = value;
    }

    /**
     * Gets the value of the participantCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getParticipantCount() {
        return participantCount;
    }

    /**
     * Sets the value of the participantCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParticipantCount(Integer value) {
        this.participantCount = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEthnicity() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEthnicity(String value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}Race" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "race"
    })
    public static class IsClassifiedBy {

        @XmlElement(name = "Race", required = true)
        protected List<Race> race;

        /**
         * Gets the value of the race property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the race property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRace().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Race }
         * 
         * 
         */
        public List<Race> getRace() {
            if (race == null) {
                race = new ArrayList<Race>();
            }
            return this.race;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}SpecimenCollectionSummary" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "specimenCollectionSummary"
    })
    public static class Provides {

        @XmlElement(name = "SpecimenCollectionSummary", required = true)
        protected List<SpecimenCollectionSummary> specimenCollectionSummary;

        /**
         * Gets the value of the specimenCollectionSummary property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the specimenCollectionSummary property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSpecimenCollectionSummary().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SpecimenCollectionSummary }
         * 
         * 
         */
        public List<SpecimenCollectionSummary> getSpecimenCollectionSummary() {
            if (specimenCollectionSummary == null) {
                specimenCollectionSummary = new ArrayList<SpecimenCollectionSummary>();
            }
            return this.specimenCollectionSummary;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}Diagnosis" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diagnosis"
    })
    public static class Receives {

        @XmlElement(name = "Diagnosis")
        protected List<Diagnosis> diagnosis;

        /**
         * Gets the value of the diagnosis property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the diagnosis property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDiagnosis().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Diagnosis }
         * 
         * 
         */
        public List<Diagnosis> getDiagnosis() {
            if (diagnosis == null) {
                diagnosis = new ArrayList<Diagnosis>();
            }
            return this.diagnosis;
        }

    }

}
