//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//


package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatientAgeGroupAtCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientAgeGroupAtCollection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="describesPatientAge" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}SpecimenCollectionSummary" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="patientAgeGroupHigh" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="patientAgeGroupLow" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientAgeGroupAtCollection", propOrder = {
    "describesPatientAge"
})
public class PatientAgeGroupAtCollection {

    protected PatientAgeGroupAtCollection.DescribesPatientAge describesPatientAge;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected Integer patientAgeGroupHigh;
    @XmlAttribute
    protected Integer patientAgeGroupLow;

    /**
     * Gets the value of the describesPatientAge property.
     * 
     * @return
     *     possible object is
     *     {@link PatientAgeGroupAtCollection.DescribesPatientAge }
     *     
     */
    public PatientAgeGroupAtCollection.DescribesPatientAge getDescribesPatientAge() {
        return describesPatientAge;
    }

    /**
     * Sets the value of the describesPatientAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientAgeGroupAtCollection.DescribesPatientAge }
     *     
     */
    public void setDescribesPatientAge(PatientAgeGroupAtCollection.DescribesPatientAge value) {
        this.describesPatientAge = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the patientAgeGroupHigh property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPatientAgeGroupHigh() {
        return patientAgeGroupHigh;
    }

    /**
     * Sets the value of the patientAgeGroupHigh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPatientAgeGroupHigh(Integer value) {
        this.patientAgeGroupHigh = value;
    }

    /**
     * Gets the value of the patientAgeGroupLow property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPatientAgeGroupLow() {
        return patientAgeGroupLow;
    }

    /**
     * Sets the value of the patientAgeGroupLow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPatientAgeGroupLow(Integer value) {
        this.patientAgeGroupLow = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}SpecimenCollectionSummary" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "specimenCollectionSummary"
    })
    public static class DescribesPatientAge {

        @XmlElement(name = "SpecimenCollectionSummary")
        protected List<SpecimenCollectionSummary> specimenCollectionSummary;

        /**
         * Gets the value of the specimenCollectionSummary property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the specimenCollectionSummary property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSpecimenCollectionSummary().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SpecimenCollectionSummary }
         * 
         * 
         */
        public List<SpecimenCollectionSummary> getSpecimenCollectionSummary() {
            if (specimenCollectionSummary == null) {
                specimenCollectionSummary = new ArrayList<SpecimenCollectionSummary>();
            }
            return this.specimenCollectionSummary;
        }

    }

}
