//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//


package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecimenCollectionContact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecimenCollectionContact">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}Person">
 *       &lt;sequence>
 *         &lt;element name="isLocatedAt" type="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}Address" form="qualified"/>
 *       &lt;/sequence>
 *       &lt;attribute name="phone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecimenCollectionContact", propOrder = {
    "isLocatedAt"
})
public class SpecimenCollectionContact
    extends Person
{

    @XmlElement(required = true)
    protected Address isLocatedAt;
    @XmlAttribute
    protected String phone;

    /**
     * Gets the value of the isLocatedAt property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getIsLocatedAt() {
        return isLocatedAt;
    }

    /**
     * Sets the value of the isLocatedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setIsLocatedAt(Address value) {
        this.isLocatedAt = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

}
