//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//


package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecimenAvailabilitySummaryProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecimenAvailabilitySummaryProfile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="restrictsAccessTo" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}CollectionProtocol" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="isAvailableToCommercialOrganizations" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isAvailableToForeignInvestigators" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isAvailableToOutsideInstitution" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isCollaborationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecimenAvailabilitySummaryProfile", propOrder = {
    "restrictsAccessTo"
})
public class SpecimenAvailabilitySummaryProfile {

    protected SpecimenAvailabilitySummaryProfile.RestrictsAccessTo restrictsAccessTo;
    @XmlAttribute
    protected Boolean isAvailableToCommercialOrganizations;
    @XmlAttribute
    protected Boolean isAvailableToForeignInvestigators;
    @XmlAttribute
    protected Boolean isAvailableToOutsideInstitution;
    @XmlAttribute
    protected Boolean isCollaborationRequired;
    @XmlAttribute
    protected Integer id;

    /**
     * Gets the value of the restrictsAccessTo property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenAvailabilitySummaryProfile.RestrictsAccessTo }
     *     
     */
    public SpecimenAvailabilitySummaryProfile.RestrictsAccessTo getRestrictsAccessTo() {
        return restrictsAccessTo;
    }

    /**
     * Sets the value of the restrictsAccessTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenAvailabilitySummaryProfile.RestrictsAccessTo }
     *     
     */
    public void setRestrictsAccessTo(SpecimenAvailabilitySummaryProfile.RestrictsAccessTo value) {
        this.restrictsAccessTo = value;
    }

    /**
     * Gets the value of the isAvailableToCommercialOrganizations property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAvailableToCommercialOrganizations() {
        return isAvailableToCommercialOrganizations;
    }

    /**
     * Sets the value of the isAvailableToCommercialOrganizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAvailableToCommercialOrganizations(Boolean value) {
        this.isAvailableToCommercialOrganizations = value;
    }

    /**
     * Gets the value of the isAvailableToForeignInvestigators property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAvailableToForeignInvestigators() {
        return isAvailableToForeignInvestigators;
    }

    /**
     * Sets the value of the isAvailableToForeignInvestigators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAvailableToForeignInvestigators(Boolean value) {
        this.isAvailableToForeignInvestigators = value;
    }

    /**
     * Gets the value of the isAvailableToOutsideInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAvailableToOutsideInstitution() {
        return isAvailableToOutsideInstitution;
    }

    /**
     * Sets the value of the isAvailableToOutsideInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAvailableToOutsideInstitution(Boolean value) {
        this.isAvailableToOutsideInstitution = value;
    }

    /**
     * Gets the value of the isCollaborationRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCollaborationRequired() {
        return isCollaborationRequired;
    }

    /**
     * Sets the value of the isCollaborationRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCollaborationRequired(Boolean value) {
        this.isCollaborationRequired = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}CollectionProtocol" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "collectionProtocol"
    })
    public static class RestrictsAccessTo {

        @XmlElement(name = "CollectionProtocol")
        protected List<CollectionProtocol> collectionProtocol;

        /**
         * Gets the value of the collectionProtocol property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the collectionProtocol property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCollectionProtocol().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CollectionProtocol }
         * 
         * 
         */
        public List<CollectionProtocol> getCollectionProtocol() {
            if (collectionProtocol == null) {
                collectionProtocol = new ArrayList<CollectionProtocol>();
            }
            return this.collectionProtocol;
        }

    }

}
