//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.02 at 08:14:09 AM CET 
//


package gme.cacore_cacore._3_2.gov_nih_nci_cbm_domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecimenCollectionSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecimenCollectionSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="qualifiesPatientAgeAtSpecimenCollection" type="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}PatientAgeGroupAtCollection" minOccurs="0" form="qualified"/>
 *         &lt;element name="undergoes" type="{gme://caCORE.caCORE/3.2/gov.nih.nci.cbm.domain.MarshallerModel}Preservation" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *       &lt;attribute name="anatomicSource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="specimenCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="specimenType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecimenCollectionSummary", propOrder = {
    "qualifiesPatientAgeAtSpecimenCollection",
    "undergoes"
})
public class SpecimenCollectionSummary {

    protected PatientAgeGroupAtCollection qualifiesPatientAgeAtSpecimenCollection;
    protected Preservation undergoes;
    @XmlAttribute
    protected String anatomicSource;
    @XmlAttribute
    protected Integer specimenCount;
    @XmlAttribute
    protected String specimenType;
    @XmlAttribute
    protected Integer id;

    /**
     * Gets the value of the qualifiesPatientAgeAtSpecimenCollection property.
     * 
     * @return
     *     possible object is
     *     {@link PatientAgeGroupAtCollection }
     *     
     */
    public PatientAgeGroupAtCollection getQualifiesPatientAgeAtSpecimenCollection() {
        return qualifiesPatientAgeAtSpecimenCollection;
    }

    /**
     * Sets the value of the qualifiesPatientAgeAtSpecimenCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientAgeGroupAtCollection }
     *     
     */
    public void setQualifiesPatientAgeAtSpecimenCollection(PatientAgeGroupAtCollection value) {
        this.qualifiesPatientAgeAtSpecimenCollection = value;
    }

    /**
     * Gets the value of the undergoes property.
     * 
     * @return
     *     possible object is
     *     {@link Preservation }
     *     
     */
    public Preservation getUndergoes() {
        return undergoes;
    }

    /**
     * Sets the value of the undergoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Preservation }
     *     
     */
    public void setUndergoes(Preservation value) {
        this.undergoes = value;
    }

    /**
     * Gets the value of the anatomicSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnatomicSource() {
        return anatomicSource;
    }

    /**
     * Sets the value of the anatomicSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnatomicSource(String value) {
        this.anatomicSource = value;
    }

    /**
     * Gets the value of the specimenCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSpecimenCount() {
        return specimenCount;
    }

    /**
     * Sets the value of the specimenCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSpecimenCount(Integer value) {
        this.specimenCount = value;
    }

    /**
     * Gets the value of the specimenType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenType() {
        return specimenType;
    }

    /**
     * Sets the value of the specimenType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenType(String value) {
        this.specimenType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

}
