version: "3.1"
services:
    molgenis:
      build:
        context: .
        args:
          WAR_FILE: target/molgenis-app-*.war

      ports:
        - 8081:8080
      environment:
        - molgenis.home=/home/molgenis
        - opencpu.uri.host=opencpu
        - elasticsearch.transport.addresses=elasticsearch:9300
        - db_uri=jdbc:postgresql://postgres/molgenis
        - db_user=molgenis
        - db_password=molgenis
        - admin.password=admin
        - MINIO_BUCKET_NAME=molgenis
        - MINIO_ENDPOINT=http://minio:9000
        - MINIO_ACCESS_KEY=molgenis
        - MINIO_SECRET_KEY=molgenis
        - "CATALINA_OPTS=-Xmx1g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
    postgres:
      image: postgres:11-alpine
      environment:
          - POSTGRES_USER=molgenis
          - POSTGRES_PASSWORD=molgenis
          - POSTGRES_DB=molgenis

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
        environment:
          - cluster.name=molgenis
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - xpack.security.enabled=false
          - discovery.type=single-node
        ulimits:
          memlock:
            soft: -1
            hard: -1
        ports:
          - 9200:9200

    opencpu:
        image: molgenis/opencpu:latest
        ports:
          - 8004:8004

    minio:
        image: minio/minio:RELEASE.2019-03-20T22-38-47Z
        volumes:
          - data:/data
        ports:
          - 9000:9000
        environment:
          MINIO_ACCESS_KEY: molgenis
          MINIO_SECRET_KEY: molgenis
        command: server /data

volumes:
  data: