<#macro TaskStatusPlugin screen>
<table>
    <thead>
    <tr>
        <th>
            Tasks Status
        </th>
        <th>
        </th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            Generated
        </td>
        <td>
        ${screen.summary.taskGenerated}
        </td>
    </tr>
    <tr>
        <td>
            Ready
        </td>
        <td>
        ${screen.summary.taskReady}
        </td>
    </tr>
    <tr>
        <td>
            Running
        </td>
        <td>
        ${screen.summary.taskRunning}
        </td>
    </tr>
    <tr>
        <td>
            Failed
        </td>
        <td>
        ${screen.summary.taskFailed}
        </td>
    </tr>
    <tr>
        <td>
            Done
        </td>
        <td>
        ${screen.summary.taskDone}
        </td>
    </tr>
    </tbody>
</table>
</#macro>