package org.molgenis.data.importer;

import java.util.List;
import java.util.Map;

import org.molgenis.data.EntityMetaData;

import com.google.auto.value.AutoValue;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;

@AutoValue
public abstract class ParsedMetaData
{
	public static ParsedMetaData create(List<? extends EntityMetaData> entities,
			Map<String, ? extends org.molgenis.data.Package> map)
	{
		// this class is generated by the @AutoValue annotation
		// In Eclipse, add target/generated-sources/annotations to the project src path.
		// Or better still, get m2e-apt on the eclipse marketplace and configure this project's
		// maven annotation processing to Automatically configure the JDT APT.
		return new AutoValue_ParsedMetaData(ImmutableList.copyOf(entities), ImmutableMap.copyOf(map));
	}

	/**
	 * Gets the entities, in resolved order.
	 * 
	 * @return
	 */
	public abstract ImmutableList<EntityMetaData> getEntities();

	/**
	 * Gets the packages
	 * 
	 * @return
	 */
	public abstract ImmutableMap<String, org.molgenis.data.Package> getPackages();

	/**
	 * Gets a specific package
	 * 
	 * @param name
	 *            the name of the package
	 * @return
	 */
	public org.molgenis.data.Package getPackage(String name)
	{
		return getPackages().get(name);
	}
}
