POST http://localhost/login?username=admin&password=admin

###

POST http://localhost/plugin/directory/export
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4K

{
  "URL": "http://localhost/menu/main/dataexplorer?entity=test_negotiator_entity1&mod=data&query%5Bq%5D%5B0%5D%5Boperator%5D=SEARCH&query%5Bq%5D%5B0%5D%5Bvalue%5D=Lorem&filter=biobank=q=ipsum",
  "entityId": "test_negotiator_entity1",
  "rsql": "*=q=Lorem;biobank=q=ipsum",
  "humanReadable": "Free text search contains Lorem and biobank contains ipsum"
}

###

POST http://localhost/plugin/directory/export
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4K

{
  "URL": "http://localhost/menu/main/dataexplorer?entity=test_negotiator_entity1&mod=data&query%5Bq%5D%5B0%5D%5Boperator%5D=SEARCH&query%5Bq%5D%5B0%5D%5Bvalue%5D=Lorem&filter=biobank=q=ipsum",
  "entityId": "test_negotiator_entity1",
  "biobankId": "test_negotiator_biobank",
  "rsql": "*=q=Lorem",
  "biobankRsql": "covid19=in=(super)",
  "humanReadable": "Free text search contains Lorem and biobank contains ipsum"
}

###

POST http://localhost/plugin/directory/export
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4K

{
  "URL": "http://localhost/menu/main/dataexplorer?entity=test_negotiator_entity1&mod=data&query%5Bq%5D%5B0%5D%5Boperator%5D=SEARCH&query%5Bq%5D%5B0%5D%5Bvalue%5D=Lorem&filter=biobank=q=ipsum",
  "entityId": "test_negotiator_entity1",
  "biobankId": "test_negotiator_biobank",
  "biobankRsql": "covid19=in=(super)",
  "humanReadable": "Free text search contains Lorem and biobank contains ipsum"
}

###