package org.molgenis.audit;

public enum AuditEventType {
  AUTHENTICATION_FAILURE,
  AUTHENTICATION_SUCCESS,
  AUTHENTICATION_SWITCH,
  AUTHORIZATION_FAILURE,
  AUTHORIZATION_SUCCESS,
  LOGOUT_SUCCESS,
  SESSION_ID_CHANGE
}
