package org.molgenis.data.semanticsearch.explain.service;

import java.util.Map.Entry;
import java.util.Set;

import org.apache.lucene.search.Explanation;
import org.molgenis.data.EntityMetaData;
import org.molgenis.data.Query;
import org.molgenis.data.QueryRule;

public interface ElasticSearchExplainService
{
	/**
	 * Get explanation for specific document in elasticSearch
	 * 
	 * @param documentId
	 * @param queryString
	 * @return
	 */
	abstract Explanation explain(Query q, EntityMetaData entityMetaData, String documentId);

	/**
	 * Deduce all the matches are generated by ElasticSearch
	 * 
	 * @param explanationBean
	 * @return
	 */
	abstract Set<Entry<String, Double>> reverseSearchQueryStrings(QueryRule disMaxQueryRule, Explanation explanation);
}
